chore: bump halo plugin devtools version
halo-sigs/plugin-highlightjs pull request #7
Opened 2023-06-28 08:45 UTC by ruibaby

- 提升 `run.halo.plugin.devtools` 插件的版本
- 升级 Gradle 的版本至 8.0
- SettingFetcher 改为 ReactiveSettingFetcher

/kind improvement

```release-note
None
```

2023-06-28 15:12 UTC, guqing commented on build.gradle
> +    id "run.halo.plugin.devtools" version "0.0.4"
可以用 0.0.5 了

2023-06-28 15:21 UTC, guqing approved these changes
/approve

2023-06-29 08:40 UTC, JohnNiang requested changes

2023-06-29 08:40 UTC, JohnNiang commented on src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
> +        }).onErrorContinue((throwable, o) -> log.warn("HighlightJSHeadProcessor process failed", throwable)).then();
推荐直接用 doOnError。

2023-06-29 09:35 UTC, ruibaby commented on src/main/java/run/halo/highlightjs/HighlightJSHeadProcessor.java
> +        }).onErrorContinue((throwable, o) -> log.warn("HighlightJSHeadProcessor process failed", throwable)).then();
Fixed

2023-06-29 09:42 UTC, JohnNiang approved these changes
/lgtm

2023-06-29 09:44 UTC, merged